import { getDb } from '../config/db';

export async function runMigrations(): Promise<void> {
  const db = getDb();
  if (!db) return;
  try {
    await db.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    await db.query(`DO $$ BEGIN CREATE TYPE user_role AS ENUM ('customer','admin','super_admin'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE kyc_status AS ENUM ('pending','under_review','approved','rejected'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE account_type AS ENUM ('checking','savings','money_market'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE account_status AS ENUM ('pending','active','frozen','closed'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE tx_type AS ENUM ('deposit','withdrawal','transfer','payment','fee','wire','ach','zelle'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE tx_status AS ENUM ('pending','processing','completed','failed','reversed'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE card_type AS ENUM ('classic','gold','platinum'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE card_app_status AS ENUM ('pending_fee','fee_paid','under_review','approved','rejected'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE card_status AS ENUM ('active','frozen','cancelled'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE loan_type AS ENUM ('personal','auto','mortgage','business'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE loan_status AS ENUM ('draft','submitted','under_review','approved','rejected','active','paid_off'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`DO $$ BEGIN CREATE TYPE alert_severity AS ENUM ('low','medium','high','critical'); EXCEPTION WHEN duplicate_object THEN null; END $$`);
    await db.query(`CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), email TEXT UNIQUE NOT NULL, phone TEXT UNIQUE, password_hash TEXT NOT NULL, role user_role NOT NULL DEFAULT 'customer', first_name TEXT NOT NULL, last_name TEXT NOT NULL, kyc_status kyc_status NOT NULL DEFAULT 'pending', kyc_reviewed_at TIMESTAMPTZ, kyc_reviewed_by UUID, mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE, mfa_secret TEXT, is_active BOOLEAN NOT NULL DEFAULT TRUE, failed_login_attempts INT NOT NULL DEFAULT 0, locked_until TIMESTAMPTZ, last_login_at TIMESTAMPTZ, last_login_ip INET, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await db.query(`CREATE TABLE IF NOT EXISTS accounts (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, account_number TEXT UNIQUE NOT NULL, routing_number TEXT NOT NULL DEFAULT '021000021', account_type account_type NOT NULL DEFAULT 'checking', status account_status NOT NULL DEFAULT 'pending', balance NUMERIC(18,2) NOT NULL DEFAULT 0.00, available_balance NUMERIC(18,2) NOT NULL DEFAULT 0.00, daily_limit NUMERIC(18,2) NOT NULL DEFAULT 2500.00, nickname TEXT, opened_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await db.query(`CREATE TABLE IF NOT EXISTS transactions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), reference_id TEXT UNIQUE NOT NULL, from_account_id UUID REFERENCES accounts(id), to_account_id UUID REFERENCES accounts(id), tx_type tx_type NOT NULL, status tx_status NOT NULL DEFAULT 'pending', amount NUMERIC(18,2) NOT NULL, fee NUMERIC(18,2) NOT NULL DEFAULT 0.00, description TEXT, metadata JSONB, ip_address INET, risk_score SMALLINT, flagged BOOLEAN NOT NULL DEFAULT FALSE, flagged_reason TEXT, processed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await db.query(`CREATE TABLE IF NOT EXISTS card_fee_config (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), card_type card_type NOT NULL UNIQUE, application_fee NUMERIC(10,2) NOT NULL DEFAULT 0.00, fee_enabled BOOLEAN NOT NULL DEFAULT TRUE, annual_fee NUMERIC(10,2) NOT NULL DEFAULT 0.00, apr_min NUMERIC(6,4) NOT NULL, apr_max NUMERIC(6,4) NOT NULL, updated_by UUID, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await db.query(`INSERT INTO card_fee_config (card_type, application_fee, annual_fee, apr_min, apr_max) VALUES ('classic',0.00,0.00,0.1899,0.2999),('gold',25.00,95.00,0.1799,0.2899),('platinum',50.00,195.00,0.1699,0.2799) ON CONFLICT (card_type) DO NOTHING`);
    await db.query(`CREATE TABLE IF NOT EXISTS card_applications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, card_type card_type NOT NULL, status card_app_status NOT NULL DEFAULT 'pending_fee', application_fee NUMERIC(10,2) NOT NULL, fee_paid_at TIMESTAMPTZ, credit_limit NUMERIC(18,2), apr NUMERIC(6,4), review_notes TEXT, reviewed_by UUID, reviewed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await db.query(`CREATE TABLE IF NOT EXISTS credit_cards (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), application_id UUID NOT NULL REFERENCES card_applications(id), user_id UUID NOT NULL REFERENCES users(id), card_type card_type NOT NULL, card_last4 CHAR(4) NOT NULL, expiry_month SMALLINT NOT NULL, expiry_year SMALLINT NOT NULL, status card_status NOT NULL DEFAULT 'active', credit_limit NUMERIC(18,2) NOT NULL, balance NUMERIC(18,2) NOT NULL DEFAULT 0.00, apr NUMERIC(6,4) NOT NULL, annual_fee NUMERIC(10,2) NOT NULL DEFAULT 0.00, issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), frozen_at TIMESTAMPTZ)`);
    await db.query(`CREATE TABLE IF NOT EXISTS loan_applications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, loan_type loan_type NOT NULL, requested_amount NUMERIC(18,2) NOT NULL, term_months SMALLINT NOT NULL, purpose TEXT, annual_income NUMERIC(18,2), status loan_status NOT NULL DEFAULT 'draft', review_notes TEXT, reviewed_by UUID, reviewed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await db.query(`CREATE TABLE IF NOT EXISTS loans (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), application_id UUID NOT NULL REFERENCES loan_applications(id), user_id UUID NOT NULL REFERENCES users(id), loan_type loan_type NOT NULL, principal NUMERIC(18,2) NOT NULL, interest_rate NUMERIC(6,4) NOT NULL, term_months SMALLINT NOT NULL, monthly_payment NUMERIC(18,2) NOT NULL, outstanding_balance NUMERIC(18,2) NOT NULL, status loan_status NOT NULL DEFAULT 'active', next_payment_date DATE, disbursed_at TIMESTAMPTZ)`);
    await db.query(`CREATE TABLE IF NOT EXISTS fraud_alerts (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id), tx_id UUID REFERENCES transactions(id), severity alert_severity NOT NULL, rule_triggered TEXT NOT NULL, risk_score SMALLINT NOT NULL, details JSONB, is_resolved BOOLEAN NOT NULL DEFAULT FALSE, resolved_by UUID, resolved_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await db.query(`CREATE TABLE IF NOT EXISTS notifications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, title TEXT NOT NULL, body TEXT NOT NULL, is_read BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await db.query(`CREATE TABLE IF NOT EXISTS audit_log (id BIGSERIAL PRIMARY KEY, actor_id UUID, action TEXT NOT NULL, entity_type TEXT, entity_id UUID, metadata JSONB, ip_address INET, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    console.log('[Migration] Done');
  } catch (e: any) {
    console.error('[Migration] Error:', e.message);
  }
}
