// Oakstones 1 Bank — Country configuration for international KYC.
// Tier-1 countries get precise national-ID labels, formats and validation.
// Every other country is selectable and uses the GENERIC config + its own currency.

export interface Country {
  code: string;   // ISO 3166-1 alpha-2
  name: string;
  currency: string; // ISO 4217
}

export interface CountryConfig {
  idLabel: string;          // what the national-ID field is called
  idPlaceholder: string;
  idHint: string;
  idMinDigits: number;      // minimum digits/characters expected (loose check)
  regionLabel: string;      // State / Province / Prefecture / Region
  postalLabel: string;      // ZIP code / Postal code / Postcode
  postalPlaceholder: string;
  citizenshipOptions: string[];
  idTypes: string[];
}

export const US_STATES = ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY","DC"];

// ---------- Tier-1 configs ----------
const CONFIGS: Record<string, CountryConfig> = {
  US: {
    idLabel: "Social Security Number (SSN / ITIN)",
    idPlaceholder: "123-45-6789",
    idHint: "Required by federal law (USA PATRIOT Act).",
    idMinDigits: 9,
    regionLabel: "State",
    postalLabel: "ZIP code",
    postalPlaceholder: "10001",
    citizenshipOptions: ["U.S. Citizen", "U.S. Permanent Resident", "Non-Resident"],
    idTypes: ["U.S. Driver's License", "State ID Card", "U.S. Passport", "Permanent Resident Card"],
  },
  CA: {
    idLabel: "Social Insurance Number (SIN)",
    idPlaceholder: "123-456-789",
    idHint: "9-digit SIN, required for Canadian account holders.",
    idMinDigits: 9,
    regionLabel: "Province / Territory",
    postalLabel: "Postal code",
    postalPlaceholder: "K1A 0B1",
    citizenshipOptions: ["Canadian Citizen", "Permanent Resident", "Non-Resident"],
    idTypes: ["Driver's Licence", "Provincial ID Card", "Canadian Passport", "Permanent Resident Card"],
  },
  GB: {
    idLabel: "National Insurance Number",
    idPlaceholder: "QQ 12 34 56 C",
    idHint: "Your NI number, e.g. QQ123456C.",
    idMinDigits: 8,
    regionLabel: "County / Region",
    postalLabel: "Postcode",
    postalPlaceholder: "SW1A 1AA",
    citizenshipOptions: ["British Citizen", "Settled Status / ILR", "Non-Resident"],
    idTypes: ["UK Driving Licence", "UK Passport", "Biometric Residence Permit"],
  },
  FR: {
    idLabel: "Numéro de Sécurité Sociale (INSEE)",
    idPlaceholder: "1 85 05 78 006 084 36",
    idHint: "13–15 digit INSEE / social security number.",
    idMinDigits: 13,
    regionLabel: "Région / Département",
    postalLabel: "Code postal",
    postalPlaceholder: "75001",
    citizenshipOptions: ["French Citizen", "EU Citizen", "Resident Permit Holder", "Non-Resident"],
    idTypes: ["Carte Nationale d'Identité", "Passeport", "Titre de Séjour", "Permis de Conduire"],
  },
  NL: {
    idLabel: "Citizen Service Number (BSN)",
    idPlaceholder: "123456782",
    idHint: "9-digit Burgerservicenummer.",
    idMinDigits: 8,
    regionLabel: "Province",
    postalLabel: "Postcode",
    postalPlaceholder: "1012 AB",
    citizenshipOptions: ["Dutch Citizen", "EU Citizen", "Resident Permit Holder", "Non-Resident"],
    idTypes: ["Nederlandse Identiteitskaart", "Paspoort", "Verblijfsvergunning", "Rijbewijs"],
  },
  DE: {
    idLabel: "Tax Identification Number (Steuer-ID)",
    idPlaceholder: "12 345 678 901",
    idHint: "11-digit steuerliche Identifikationsnummer.",
    idMinDigits: 11,
    regionLabel: "Bundesland",
    postalLabel: "Postleitzahl (PLZ)",
    postalPlaceholder: "10115",
    citizenshipOptions: ["German Citizen", "EU Citizen", "Resident Permit Holder", "Non-Resident"],
    idTypes: ["Personalausweis", "Reisepass", "Aufenthaltstitel", "Führerschein"],
  },
  BR: {
    idLabel: "CPF (Cadastro de Pessoas Físicas)",
    idPlaceholder: "123.456.789-09",
    idHint: "11-digit CPF number.",
    idMinDigits: 11,
    regionLabel: "Estado",
    postalLabel: "CEP",
    postalPlaceholder: "01310-100",
    citizenshipOptions: ["Brazilian Citizen", "Permanent Resident", "Non-Resident"],
    idTypes: ["RG (Registro Geral)", "CNH (Driver's License)", "Passaporte"],
  },
  MX: {
    idLabel: "CURP",
    idPlaceholder: "GOMC900514HDFRRL09",
    idHint: "18-character Clave Única de Registro de Población.",
    idMinDigits: 18,
    regionLabel: "Estado",
    postalLabel: "Código postal",
    postalPlaceholder: "06600",
    citizenshipOptions: ["Mexican Citizen", "Permanent Resident", "Non-Resident"],
    idTypes: ["INE / IFE Card", "Pasaporte", "Cédula Profesional", "Licencia de Conducir"],
  },
  CN: {
    idLabel: "Resident Identity Card Number (居民身份证)",
    idPlaceholder: "110101199003077758",
    idHint: "18-digit resident identity card number.",
    idMinDigits: 18,
    regionLabel: "Province (省)",
    postalLabel: "Postal code (邮编)",
    postalPlaceholder: "100000",
    citizenshipOptions: ["Chinese Citizen", "Permanent Resident", "Non-Resident"],
    idTypes: ["Resident Identity Card", "Passport (护照)"],
  },
  JP: {
    idLabel: "My Number (Individual Number / マイナンバー)",
    idPlaceholder: "1234 5678 9012",
    idHint: "12-digit Individual Number.",
    idMinDigits: 12,
    regionLabel: "Prefecture (都道府県)",
    postalLabel: "Postal code (〒)",
    postalPlaceholder: "100-0001",
    citizenshipOptions: ["Japanese Citizen", "Permanent Resident", "Non-Resident"],
    idTypes: ["My Number Card", "Driver's License (運転免許証)", "Passport", "Residence Card (在留カード)"],
  },
};

const GENERIC: CountryConfig = {
  idLabel: "National ID / Tax Number",
  idPlaceholder: "Your national identification number",
  idHint: "Enter your government-issued national ID or tax number.",
  idMinDigits: 4,
  regionLabel: "State / Province / Region",
  postalLabel: "Postal code",
  postalPlaceholder: "Postal code",
  citizenshipOptions: ["Citizen", "Permanent Resident", "Non-Resident"],
  idTypes: ["National ID Card", "Passport", "Driver's License", "Residence Permit"],
};

export function getCountryConfig(code?: string): CountryConfig {
  if (!code) return CONFIGS.US;
  return CONFIGS[code.toUpperCase()] ?? GENERIC;
}

export function currencyForCountry(code?: string): string {
  if (!code) return "USD";
  const c = COUNTRIES.find((x) => x.code === code.toUpperCase());
  return c?.currency ?? "USD";
}

// ---------- Full selectable country list (Tier-1 first, then A–Z) ----------
export const COUNTRIES: Country[] = [
  { code: "US", name: "United States", currency: "USD" },
  { code: "CA", name: "Canada", currency: "CAD" },
  { code: "GB", name: "United Kingdom", currency: "GBP" },
  { code: "FR", name: "France", currency: "EUR" },
  { code: "NL", name: "Netherlands", currency: "EUR" },
  { code: "DE", name: "Germany", currency: "EUR" },
  { code: "BR", name: "Brazil", currency: "BRL" },
  { code: "MX", name: "Mexico", currency: "MXN" },
  { code: "CN", name: "China", currency: "CNY" },
  { code: "JP", name: "Japan", currency: "JPY" },
  { code: "AF", name: "Afghanistan", currency: "AFN" },
  { code: "AL", name: "Albania", currency: "ALL" },
  { code: "DZ", name: "Algeria", currency: "DZD" },
  { code: "AD", name: "Andorra", currency: "EUR" },
  { code: "AO", name: "Angola", currency: "AOA" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD" },
  { code: "AR", name: "Argentina", currency: "ARS" },
  { code: "AM", name: "Armenia", currency: "AMD" },
  { code: "AU", name: "Australia", currency: "AUD" },
  { code: "AT", name: "Austria", currency: "EUR" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN" },
  { code: "BS", name: "Bahamas", currency: "BSD" },
  { code: "BH", name: "Bahrain", currency: "BHD" },
  { code: "BD", name: "Bangladesh", currency: "BDT" },
  { code: "BB", name: "Barbados", currency: "BBD" },
  { code: "BY", name: "Belarus", currency: "BYN" },
  { code: "BE", name: "Belgium", currency: "EUR" },
  { code: "BZ", name: "Belize", currency: "BZD" },
  { code: "BJ", name: "Benin", currency: "XOF" },
  { code: "BT", name: "Bhutan", currency: "BTN" },
  { code: "BO", name: "Bolivia", currency: "BOB" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM" },
  { code: "BW", name: "Botswana", currency: "BWP" },
  { code: "BN", name: "Brunei", currency: "BND" },
  { code: "BG", name: "Bulgaria", currency: "BGN" },
  { code: "BF", name: "Burkina Faso", currency: "XOF" },
  { code: "BI", name: "Burundi", currency: "BIF" },
  { code: "CV", name: "Cabo Verde", currency: "CVE" },
  { code: "KH", name: "Cambodia", currency: "KHR" },
  { code: "CM", name: "Cameroon", currency: "XAF" },
  { code: "CF", name: "Central African Republic", currency: "XAF" },
  { code: "TD", name: "Chad", currency: "XAF" },
  { code: "CL", name: "Chile", currency: "CLP" },
  { code: "CO", name: "Colombia", currency: "COP" },
  { code: "KM", name: "Comoros", currency: "KMF" },
  { code: "CG", name: "Congo (Republic)", currency: "XAF" },
  { code: "CD", name: "Congo (DRC)", currency: "CDF" },
  { code: "CR", name: "Costa Rica", currency: "CRC" },
  { code: "CI", name: "Côte d'Ivoire", currency: "XOF" },
  { code: "HR", name: "Croatia", currency: "EUR" },
  { code: "CU", name: "Cuba", currency: "CUP" },
  { code: "CY", name: "Cyprus", currency: "EUR" },
  { code: "CZ", name: "Czechia", currency: "CZK" },
  { code: "DK", name: "Denmark", currency: "DKK" },
  { code: "DJ", name: "Djibouti", currency: "DJF" },
  { code: "DM", name: "Dominica", currency: "XCD" },
  { code: "DO", name: "Dominican Republic", currency: "DOP" },
  { code: "EC", name: "Ecuador", currency: "USD" },
  { code: "EG", name: "Egypt", currency: "EGP" },
  { code: "SV", name: "El Salvador", currency: "USD" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF" },
  { code: "ER", name: "Eritrea", currency: "ERN" },
  { code: "EE", name: "Estonia", currency: "EUR" },
  { code: "SZ", name: "Eswatini", currency: "SZL" },
  { code: "ET", name: "Ethiopia", currency: "ETB" },
  { code: "FJ", name: "Fiji", currency: "FJD" },
  { code: "FI", name: "Finland", currency: "EUR" },
  { code: "GA", name: "Gabon", currency: "XAF" },
  { code: "GM", name: "Gambia", currency: "GMD" },
  { code: "GE", name: "Georgia", currency: "GEL" },
  { code: "GH", name: "Ghana", currency: "GHS" },
  { code: "GR", name: "Greece", currency: "EUR" },
  { code: "GD", name: "Grenada", currency: "XCD" },
  { code: "GT", name: "Guatemala", currency: "GTQ" },
  { code: "GN", name: "Guinea", currency: "GNF" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF" },
  { code: "GY", name: "Guyana", currency: "GYD" },
  { code: "HT", name: "Haiti", currency: "HTG" },
  { code: "HN", name: "Honduras", currency: "HNL" },
  { code: "HK", name: "Hong Kong", currency: "HKD" },
  { code: "HU", name: "Hungary", currency: "HUF" },
  { code: "IS", name: "Iceland", currency: "ISK" },
  { code: "IN", name: "India", currency: "INR" },
  { code: "ID", name: "Indonesia", currency: "IDR" },
  { code: "IR", name: "Iran", currency: "IRR" },
  { code: "IQ", name: "Iraq", currency: "IQD" },
  { code: "IE", name: "Ireland", currency: "EUR" },
  { code: "IL", name: "Israel", currency: "ILS" },
  { code: "IT", name: "Italy", currency: "EUR" },
  { code: "JM", name: "Jamaica", currency: "JMD" },
  { code: "JO", name: "Jordan", currency: "JOD" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT" },
  { code: "KE", name: "Kenya", currency: "KES" },
  { code: "KI", name: "Kiribati", currency: "AUD" },
  { code: "KW", name: "Kuwait", currency: "KWD" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS" },
  { code: "LA", name: "Laos", currency: "LAK" },
  { code: "LV", name: "Latvia", currency: "EUR" },
  { code: "LB", name: "Lebanon", currency: "LBP" },
  { code: "LS", name: "Lesotho", currency: "LSL" },
  { code: "LR", name: "Liberia", currency: "LRD" },
  { code: "LY", name: "Libya", currency: "LYD" },
  { code: "LI", name: "Liechtenstein", currency: "CHF" },
  { code: "LT", name: "Lithuania", currency: "EUR" },
  { code: "LU", name: "Luxembourg", currency: "EUR" },
  { code: "MO", name: "Macao", currency: "MOP" },
  { code: "MG", name: "Madagascar", currency: "MGA" },
  { code: "MW", name: "Malawi", currency: "MWK" },
  { code: "MY", name: "Malaysia", currency: "MYR" },
  { code: "MV", name: "Maldives", currency: "MVR" },
  { code: "ML", name: "Mali", currency: "XOF" },
  { code: "MT", name: "Malta", currency: "EUR" },
  { code: "MH", name: "Marshall Islands", currency: "USD" },
  { code: "MR", name: "Mauritania", currency: "MRU" },
  { code: "MU", name: "Mauritius", currency: "MUR" },
  { code: "FM", name: "Micronesia", currency: "USD" },
  { code: "MD", name: "Moldova", currency: "MDL" },
  { code: "MC", name: "Monaco", currency: "EUR" },
  { code: "MN", name: "Mongolia", currency: "MNT" },
  { code: "ME", name: "Montenegro", currency: "EUR" },
  { code: "MA", name: "Morocco", currency: "MAD" },
  { code: "MZ", name: "Mozambique", currency: "MZN" },
  { code: "MM", name: "Myanmar", currency: "MMK" },
  { code: "NA", name: "Namibia", currency: "NAD" },
  { code: "NR", name: "Nauru", currency: "AUD" },
  { code: "NP", name: "Nepal", currency: "NPR" },
  { code: "NZ", name: "New Zealand", currency: "NZD" },
  { code: "NI", name: "Nicaragua", currency: "NIO" },
  { code: "NE", name: "Niger", currency: "XOF" },
  { code: "NG", name: "Nigeria", currency: "NGN" },
  { code: "KP", name: "North Korea", currency: "KPW" },
  { code: "MK", name: "North Macedonia", currency: "MKD" },
  { code: "NO", name: "Norway", currency: "NOK" },
  { code: "OM", name: "Oman", currency: "OMR" },
  { code: "PK", name: "Pakistan", currency: "PKR" },
  { code: "PW", name: "Palau", currency: "USD" },
  { code: "PA", name: "Panama", currency: "USD" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK" },
  { code: "PY", name: "Paraguay", currency: "PYG" },
  { code: "PE", name: "Peru", currency: "PEN" },
  { code: "PH", name: "Philippines", currency: "PHP" },
  { code: "PL", name: "Poland", currency: "PLN" },
  { code: "PT", name: "Portugal", currency: "EUR" },
  { code: "QA", name: "Qatar", currency: "QAR" },
  { code: "RO", name: "Romania", currency: "RON" },
  { code: "RU", name: "Russia", currency: "RUB" },
  { code: "RW", name: "Rwanda", currency: "RWF" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD" },
  { code: "LC", name: "Saint Lucia", currency: "XCD" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD" },
  { code: "WS", name: "Samoa", currency: "WST" },
  { code: "SM", name: "San Marino", currency: "EUR" },
  { code: "ST", name: "São Tomé and Príncipe", currency: "STN" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR" },
  { code: "SN", name: "Senegal", currency: "XOF" },
  { code: "RS", name: "Serbia", currency: "RSD" },
  { code: "SC", name: "Seychelles", currency: "SCR" },
  { code: "SL", name: "Sierra Leone", currency: "SLE" },
  { code: "SG", name: "Singapore", currency: "SGD" },
  { code: "SK", name: "Slovakia", currency: "EUR" },
  { code: "SI", name: "Slovenia", currency: "EUR" },
  { code: "SB", name: "Solomon Islands", currency: "SBD" },
  { code: "SO", name: "Somalia", currency: "SOS" },
  { code: "ZA", name: "South Africa", currency: "ZAR" },
  { code: "KR", name: "South Korea", currency: "KRW" },
  { code: "SS", name: "South Sudan", currency: "SSP" },
  { code: "ES", name: "Spain", currency: "EUR" },
  { code: "LK", name: "Sri Lanka", currency: "LKR" },
  { code: "SD", name: "Sudan", currency: "SDG" },
  { code: "SR", name: "Suriname", currency: "SRD" },
  { code: "SE", name: "Sweden", currency: "SEK" },
  { code: "CH", name: "Switzerland", currency: "CHF" },
  { code: "SY", name: "Syria", currency: "SYP" },
  { code: "TW", name: "Taiwan", currency: "TWD" },
  { code: "TJ", name: "Tajikistan", currency: "TJS" },
  { code: "TZ", name: "Tanzania", currency: "TZS" },
  { code: "TH", name: "Thailand", currency: "THB" },
  { code: "TL", name: "Timor-Leste", currency: "USD" },
  { code: "TG", name: "Togo", currency: "XOF" },
  { code: "TO", name: "Tonga", currency: "TOP" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD" },
  { code: "TN", name: "Tunisia", currency: "TND" },
  { code: "TR", name: "Türkiye", currency: "TRY" },
  { code: "TM", name: "Turkmenistan", currency: "TMT" },
  { code: "TV", name: "Tuvalu", currency: "AUD" },
  { code: "UG", name: "Uganda", currency: "UGX" },
  { code: "UA", name: "Ukraine", currency: "UAH" },
  { code: "AE", name: "United Arab Emirates", currency: "AED" },
  { code: "UY", name: "Uruguay", currency: "UYU" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS" },
  { code: "VU", name: "Vanuatu", currency: "VUV" },
  { code: "VE", name: "Venezuela", currency: "VES" },
  { code: "VN", name: "Vietnam", currency: "VND" },
  { code: "YE", name: "Yemen", currency: "YER" },
  { code: "ZM", name: "Zambia", currency: "ZMW" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWG" },
];
